
module.exports = {
    ROLE_PIONEER: 'PIONEER',
    ROLE_BUILDER: 'BUILDER',
    ROLE_HARVESTER: 'HARVESTER',
    ROLE_TRANSPORTER: 'TRANSPORTER',
    ROLE_CARETAKER: 'CARETAKER',
    ROLE_SPAWNKEEPER: 'SPAWNKEEPER',
    ROLE_PUMP: 'PUMP',
    ROLE_SIMCREEP: 'SIMCREEP',
};