
module.exports = {
    ROLE_PIONEER: 'PIONEER',
    ROLE_HARVESTER: 'HARVESTER',
    ROLE_TRANSPORTER: 'TRANSPORTER',
    ROLE_CIV_TRANSPORTER: 'CIV_TRANSPORTER',
    ROLE_CARETAKER: 'CARETAKER',
    ROLE_SPAWNKEEPER: 'SPAWNKEEPER',
    ROLE_PUMP: 'PUMP',
    ROLE_SIMCREEP: 'SIMCREEP',
    ROLE_DEFENDER: 'DEFENDER',
    ROLE_SCOUT: 'SCOUT',

    SOCIETY_LEVEL_OUTPOST: 1,
    SOCIETY_LEVEL_CITY: 2,
    SOCIETY_LEVEL_CIVILIZATION: 3,

    EXPLORE_UNKNOWN: 'UNKNOWN',
    EXPLORE_MY_CONTROL: 'MY',
    EXPLORE_MY_OPERATION: 'MY_OP',
    EXPLORE_NEUTRAL: 'NEUTRAL',
    EXPLORE_ENEMY_CONTROL: 'ENEMY',
    EXPLORE_ENEMY_OPERATION: 'ENEMY_OP',

    EXPLORE_TYPE_CONTROLLER_SOURCE: 'CTRL_SOURCE',
    EXPLORE_TYPE_SOURCE_ONLY: 'SOURCES'
};